version: 2

build:
  image: latest

python:
  version: 3
  install:
    - requirements: ./requirements-docs.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py
