version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: ./requirements-docs.txt
    - path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py
