name: Lint&Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache PIP
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-pip
    - name: Cache Poetry Virtualenvs
      uses: actions/cache@v1
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-poetry
    - name: Cache pre-commit
      uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: ${{ runner.os }}-pre-commit
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        make POETRY_EXTRAS=lint init_by_poetry
    - name: Lint
      run: |
        make check-all

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache PIP
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-pip
    - name: Cache Poetry Virtualenvs
      uses: actions/cache@v1
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-poetry
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        make POETRY_EXTRAS= init_by_poetry
    - name: Cache Nox Virtualenvs
      uses: actions/cache@v1
      with:
        path: .nox
        key: ${{ runner.os }}-nox-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-nox
    - name: Test by nox
      run: |
        make nox
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # Repository upload token - get it from codecov.io
        token: ${{ secrets.CODECOV_TOKEN }}
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: false
